name: Automated API tests using Postman CLI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install depedencies
        run: npm ci

      - name: Building the application
        run: npm run build --if-present

      - name: Create fresh database
        run: npx prisma migrate reset && npx prisma db push
        
      - name: Automated api tests
        run: curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
        run: postman collection run "12125462-49adb49d-5ed9-47b5-ada2-db8b42eaf866" -e "12125462-8004cb65-1f61-4cbe-b47c-dedac12d9fc6"